// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeDXbuA7IvGYYwY6vKoYPccpHR_MjFKDY',
    appId: '1:555078761697:web:3a636e1b4b2651b8110ba0',
    messagingSenderId: '555078761697',
    projectId: 'growr-90b14',
    authDomain: 'growr-90b14.firebaseapp.com',
    storageBucket: 'growr-90b14.firebasestorage.app',
    measurementId: 'G-TEHEPT8BVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdCWFtuQYH2gRzqfYDl5OFkfO_nTHFIg8',
    appId: '1:555078761697:android:748ec8f9ddb758cf110ba0',
    messagingSenderId: '555078761697',
    projectId: 'growr-90b14',
    storageBucket: 'growr-90b14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClKMGx3JFmSadGw-rEngHI8G9FzR8HCAI',
    appId: '1:555078761697:ios:b913438e476bc97f110ba0',
    messagingSenderId: '555078761697',
    projectId: 'growr-90b14',
    storageBucket: 'growr-90b14.firebasestorage.app',
    androidClientId: '555078761697-hoqh85mi2dqaqf4gt5eqigv8013hbdai.apps.googleusercontent.com',
    iosClientId: '555078761697-793jc16211voan0cftae3fliirq77eab.apps.googleusercontent.com',
    iosBundleId: 'com.diginuance.growrr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClKMGx3JFmSadGw-rEngHI8G9FzR8HCAI',
    appId: '1:555078761697:ios:b913438e476bc97f110ba0',
    messagingSenderId: '555078761697',
    projectId: 'growr-90b14',
    storageBucket: 'growr-90b14.firebasestorage.app',
    androidClientId: '555078761697-hoqh85mi2dqaqf4gt5eqigv8013hbdai.apps.googleusercontent.com',
    iosClientId: '555078761697-793jc16211voan0cftae3fliirq77eab.apps.googleusercontent.com',
    iosBundleId: 'com.diginuance.growrr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeDXbuA7IvGYYwY6vKoYPccpHR_MjFKDY',
    appId: '1:555078761697:web:0930e71dca731761110ba0',
    messagingSenderId: '555078761697',
    projectId: 'growr-90b14',
    authDomain: 'growr-90b14.firebaseapp.com',
    storageBucket: 'growr-90b14.firebasestorage.app',
    measurementId: 'G-P8N7GKHQRT',
  );

}